# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81231d6f018f198c3ba2863e006e7df1b379e138e968b1143d65e2160c128eeb3cae93fead3891e71a232b2f4840e527af62768b65a2d9dd484b4ef2bbe6051f

test:
  secret_key_base: 46bccafaf8bcfac2bfd53be99210df6e4ecf09d2b53e5bfb940264c37db62bdc64f9fe9181f8abc780c4e27387e4686410d7ee4b5213fdd425fa2fa002b1ed23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
